# Generated by Django 3.1.5 on 2021-08-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_margin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_link',
            field=models.CharField(default='/static/assets/img/default.jpg', max_length=200),
        ),
    ]
