# Generated by Django 3.1.5 on 2021-08-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210821_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='datum',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='factuur_nummer',
            new_name='invoice_nr',
        ),
        migrations.AddField(
            model_name='invoice',
            name='products',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='invoice',
            name='totalin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='totalout',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='supplier',
            field=models.CharField(max_length=50),
        ),
    ]
