# Generated by Django 3.1.5 on 2021-09-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_invoice_totalmargin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_nr',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='products',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='totalin',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='totalmargin',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='totalout',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
    ]
