# Generated by Django 2.2.10 on 2021-10-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210907_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_nr',
            field=models.IntegerField(),
        ),
    ]
